# Generated by Django 2.0 on 2017-12-13 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_created=True, auto_now=True)),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('slug', models.SlugField(allow_unicode=True, help_text='자동 입력', max_length=100, null=True, unique=True, verbose_name='SLUG')),
                ('tape_info', models.TextField(blank=True, null=True, verbose_name='Tape INFO')),
                ('lyrics', models.TextField(blank=True, null=True, verbose_name='lyrics')),
                ('hashtag', models.CharField(blank=True, max_length=255, null=True, verbose_name='해시태그')),
                ('genre', models.CharField(blank=True, max_length=255, null=True, verbose_name='장르')),
                ('image_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='이미지 URL')),
                ('download_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='다운로드 URL')),
                ('waveform_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Waveform URL')),
                ('comments', models.IntegerField(default=0, verbose_name='댓글 수')),
                ('view_count', models.IntegerField(default=0, verbose_name='조회 수')),
                ('likes', models.IntegerField(default=0, verbose_name='좋아요')),
                ('clips', models.IntegerField(default=0, verbose_name='구독')),
                ('track_score', models.IntegerField(default=0, verbose_name='트랙 점수')),
                ('grade', models.IntegerField(default=0, verbose_name='등급')),
                ('is_deleted', models.BooleanField(default=False, help_text='사용자가 게시물을 삭제 했을 경우', verbose_name='삭제여부')),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name_plural': '트랙',
            },
        ),
    ]
