# Generated by Django 2.0 on 2017-12-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
