# Generated by Django 2.0 on 2017-12-15 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_auto_20171213_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='is_deleted',
        ),
    ]
