# Generated by Django 2.0 on 2017-12-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0003_remove_track_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='grade',
        ),
        migrations.AddField(
            model_name='track',
            name='on_stage',
            field=models.IntegerField(default=0, verbose_name='온스테이지'),
        ),
    ]
