# Generated by Django 2.0 on 2017-12-18 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracks', '0004_auto_20171215_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeleteTrack',
            fields=[
                ('create_date', models.DateTimeField(auto_created=True, auto_now=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('slug', models.SlugField(allow_unicode=True, help_text='자동 입력', max_length=100, null=True, unique=True, verbose_name='SLUG')),
                ('tape_info', models.TextField(blank=True, null=True, verbose_name='Tape INFO')),
                ('lyrics', models.TextField(blank=True, null=True, verbose_name='lyrics')),
                ('hashtag', models.CharField(blank=True, max_length=255, null=True, verbose_name='해시태그')),
                ('genre', models.CharField(blank=True, max_length=255, null=True, verbose_name='장르')),
                ('image_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='이미지 URL')),
                ('download_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='다운로드 URL')),
                ('waveform_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Waveform URL')),
                ('comments', models.IntegerField(default=0, verbose_name='댓글 수')),
                ('view_count', models.IntegerField(default=0, verbose_name='조회 수')),
                ('likes', models.IntegerField(default=0, verbose_name='좋아요')),
                ('clips', models.IntegerField(default=0, verbose_name='구독')),
                ('track_score', models.IntegerField(default=0, verbose_name='트랙 점수')),
                ('on_stage', models.IntegerField(default=0, verbose_name='온스테이지')),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delete_tracks', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name_plural': '삭제된 트랙',
                'ordering': ['-create_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['-create_date'], 'verbose_name_plural': '트랙'},
        ),
    ]
