# Generated by Django 2.0 on 2017-12-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0008_auto_20171218_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='create_date',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='on_stage',
            field=models.IntegerField(db_index=True, default=0, verbose_name='온스테이지'),
        ),
    ]
