# Generated by Django 2.0 on 2017-12-18 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0010_trackcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracks.TrackComment'),
        ),
    ]
