# Generated by Django 2.0 on 2017-12-18 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0013_auto_20171218_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tracks.TrackComment', verbose_name='부모 댓글'),
        ),
    ]
