# Generated by Django 2.0 on 2017-12-19 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0017_auto_20171219_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tracks.TrackComment', verbose_name='부모 댓글'),
        ),
        migrations.AlterField(
            model_name='trackcomment',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='tracks.Track', verbose_name='트랙'),
        ),
    ]
