# Generated by Django 2.0 on 2017-12-19 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0018_auto_20171219_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deletetrack',
            name='user',
        ),
        migrations.AddField(
            model_name='track',
            name='sc_track_id',
            field=models.IntegerField(null=True, verbose_name='트랙 ID'),
        ),
        migrations.DeleteModel(
            name='DeleteTrack',
        ),
    ]
