# Generated by Django 2.0 on 2017-12-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0019_auto_20171219_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='트랙을 삭제하는 대신 이부분을 체크 해제하세요.', verbose_name='삭제여부'),
        ),
        migrations.AlterField(
            model_name='track',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
