# Generated by Django 2.0 on 2017-12-19 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0020_auto_20171219_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='sc_track_id',
            new_name='track_id',
        ),
    ]
