# Generated by Django 2.0 on 2017-12-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0021_auto_20171219_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackcomment',
            name='is_delete',
        ),
        migrations.AddField(
            model_name='trackcomment',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='트랙을 삭제하는 대신 이부분을 체크 하세요.', verbose_name='삭제여부'),
        ),
        migrations.AlterField(
            model_name='track',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='트랙을 삭제하는 대신 이부분을 체크 하세요.', verbose_name='삭제여부'),
        ),
    ]
