# Generated by Django 2.0 on 2017-12-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0022_auto_20171219_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackcomment',
            name='create_date',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='trackcomment',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='댓글을 삭제하는 대신 이부분을 체크 하세요.', verbose_name='삭제여부'),
        ),
    ]
