# Generated by Django 2.0 on 2017-12-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0023_auto_20171219_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='track_id',
            field=models.IntegerField(null=True, unique=True, verbose_name='트랙 ID'),
        ),
    ]
