# Generated by Django 2.0 on 2018-03-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0024_auto_20171219_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='곡 길이'),
        ),
        migrations.AlterField(
            model_name='track',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
