# Generated by Django 2.0 on 2017-12-13 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_created=True, auto_now=True)),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('slug', models.SlugField(allow_unicode=True, help_text='자동 입력', max_length=100, null=True, unique=True, verbose_name='SLUG')),
                ('content', models.TextField(verbose_name='내용')),
                ('is_deleted', models.BooleanField(default=False, help_text='사용자가 게시물을 삭제 했을 경우', verbose_name='삭제여부')),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name_plural': '자유게시판',
            },
        ),
    ]
