# Generated by Django 2.0 on 2017-12-12 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name_plural': '사용자 계정'},
        ),
    ]
