# Generated by Django 2.0 on 2017-12-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20171212_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='authlog',
            name='status',
            field=models.CharField(default='Success', max_length=50),
        ),
    ]
