# Generated by Django 2.0 on 2017-12-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_authlog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authlog',
            name='status',
            field=models.CharField(default='success', max_length=50),
        ),
    ]
