# Generated by Django 2.0 on 2017-12-15 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20171215_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authlog',
            old_name='status',
            new_name='state',
        ),
    ]
