# Generated by Django 2.0 on 2017-12-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20171215_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_block',
            field=models.BooleanField(default=False, help_text='사용자 블락처리 할때 선택', verbose_name='블락여부'),
        ),
    ]
