# Generated by Django 2.0 on 2017-12-18 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_user_is_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeleteUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delete_date', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='삭제일')),
                ('provider', models.CharField(max_length=32)),
                ('uid', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delete_social_auth', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '삭제된 계정',
                'ordering': ['-delete_date'],
            },
        ),
    ]
