# Generated by Django 2.0 on 2017-12-21 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_deleteuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mailing_agree',
            field=models.BooleanField(default=False, help_text='수신 동의 여부', verbose_name='메일 수신여부'),
        ),
    ]
