# Generated by Django 2.0 on 2018-03-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_mailing_agree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mailing_agree',
            field=models.BooleanField(default=False, help_text='광고성 메일 수신 동의 여부', verbose_name='메일 수신여부'),
        ),
    ]
